baseURL = "https://davidkarlsson.tech/"
languageCode = "en-us"
title = "davidkarlsson.tech"
disableKinds = ["taxonomy", "taxonomyTerm"]
enableEmoji = true

[author]
firstname = "David"
lastname = "Karlsson"

[markup]
  [markup.highlight]
    style = "monokailight"

[params.meta]
description = "Personal website and blog of technical writer David Karlsson"

[params.contact]
email = "hello@davidkarlsson.tech"
phone = "+4670-224-26-47"
linkedin = "https://www.linkedin.com/in/david-karlsson-7b533449/"
facebook = "https://www.facebook.com/wintastic"

[params.GitHub]
RepoURL = "https://github.com/dvdksn/davidkarlsson.tech"
Branch = "master"